package jcolibri.gui.component;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;

/**
 * 
 * @author Juan José Bello
 */
public class OrderableListPanel extends javax.swing.JPanel {
	private static final long serialVersionUID = 1L;

	DefaultListModel model;

	/** Creates new form OrderableListPanel */
	public OrderableListPanel() {
		initComponents();
		itemList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		model = new DefaultListModel();
		itemList.setModel(model);
	}

	public OrderableListPanel(List list) {
		this();
		myInitComponents(list);
	}

	public void setData(List list) {
		if (list != null)
			myInitComponents(list);
	}

	public void removeSelected() {
		if (itemList.getSelectedIndex() >= 0) {
			model.removeElementAt(itemList.getSelectedIndex());
		}
	}

	private void myInitComponents(List list) {
		for (Iterator it = list.iterator(); it.hasNext();) {
			model.addElement(it.next());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() { // GEN-BEGIN:initComponents
		orderableListPanel = new javax.swing.JPanel();
		orderButtonsPanel = new javax.swing.JPanel();
		upButton = new javax.swing.JButton();
		downButton = new javax.swing.JButton();
		listScrollPane = new javax.swing.JScrollPane();
		itemList = new javax.swing.JList();

		setLayout(new java.awt.BorderLayout());

		orderableListPanel.setLayout(new java.awt.BorderLayout());

		orderButtonsPanel.setLayout(new javax.swing.BoxLayout(
				orderButtonsPanel, javax.swing.BoxLayout.Y_AXIS));

		orderButtonsPanel.setPreferredSize(new java.awt.Dimension(20, 20));
		upButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/jcolibri/resources/up.gif")));
		upButton.setToolTipText("Move task up");
		upButton.setMaximumSize(new java.awt.Dimension(20, 20));
		upButton.setMinimumSize(new java.awt.Dimension(20, 20));
		upButton.setPreferredSize(new java.awt.Dimension(20, 20));
		upButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				upButtonActionPerformed(evt);
			}
		});

		orderButtonsPanel.add(upButton);

		downButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/jcolibri/resources/down.gif")));
		downButton.setToolTipText("Move task down");
		downButton.setMaximumSize(new java.awt.Dimension(20, 20));
		downButton.setMinimumSize(new java.awt.Dimension(20, 20));
		downButton.setPreferredSize(new java.awt.Dimension(20, 20));
		downButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				downButtonActionPerformed(evt);
			}
		});

		orderButtonsPanel.add(downButton);

		orderableListPanel.add(orderButtonsPanel, java.awt.BorderLayout.EAST);

		listScrollPane.setViewportView(itemList);

		orderableListPanel.add(listScrollPane, java.awt.BorderLayout.CENTER);

		add(orderableListPanel, java.awt.BorderLayout.CENTER);

	} // GEN-END:initComponents

	private void downButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// GEN-FIRST:event_downButtonActionPerformed
		int index = itemList.getSelectedIndex();
		if (index != -1 && index != model.getSize() - 1) {
			Object o = itemList.getSelectedValue();
			model.removeElementAt(index);
			model.add(index + 1, o);
			itemList.setSelectedIndex(index + 1);
		}
	} // GEN-LAST:event_downButtonActionPerformed

	private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// GEN-FIRST:event_upButtonActionPerformed
		int index = itemList.getSelectedIndex();
		if (index > 0) {
			Object o = itemList.getSelectedValue();
			model.removeElementAt(index);
			model.add(index - 1, o);
			itemList.setSelectedIndex(index - 1);
		}
	} // GEN-LAST:event_upButtonActionPerformed

	public List getItems() {
		return Arrays.asList(model.toArray());
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton downButton;

	private javax.swing.JList itemList;

	private javax.swing.JScrollPane listScrollPane;

	private javax.swing.JPanel orderButtonsPanel;

	private javax.swing.JPanel orderableListPanel;

	private javax.swing.JButton upButton;

	// End of variables declaration//GEN-END:variables

	public static void main(String[] arga) {
		JFrame frame = new JFrame();
		ArrayList list = new ArrayList();
		list.add("Hola");
		list.add("como");
		list.add("Estas");
		frame.getContentPane().add(new OrderableListPanel(list));
		frame.setBounds(10, 10, 400, 400);
		frame.setVisible(true);
	}
}
