package jcolibri.gui;

import javax.swing.JOptionPane;

import jcolibri.cbrcore.CBRTask;
import jcolibri.cbrcore.PrototypeTaskPkgReg;
import jcolibri.util.CBRLogger;

/**
 * 
 * @author Juan José Bello
 */
public class EdiTaskFrame extends javax.swing.JInternalFrame {
	private static final long serialVersionUID = 1L;

	private PrototypeTaskPkgReg ptPkgReg;

	private CBRTask task;

	private boolean editMode;

	/**
	 * Creates new form AddTaskFrame- editMode = true if we are editing an
	 * existing task, editMode = false if the task is new.
	 */
	public EdiTaskFrame(boolean editMode, PrototypeTaskPkgReg ptPkgReg,
			CBRTask task) {
		this.ptPkgReg = ptPkgReg;
		this.task = task;
		this.editMode = editMode;
		initComponents();
		myInitComponents();
	}

	/**
	 * This method is called from within the constructor and after
	 * initComponents method to initialize the form.
	 */
	private void myInitComponents() {
		taskNameField.setText(task.getName());
		taskDescriptionArea.setText(task.getDescription());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		java.awt.GridBagConstraints gridBagConstraints;

		mainPanel = new javax.swing.JPanel();
		textPanel = new javax.swing.JPanel();
		taskNamelabel = new javax.swing.JLabel();
		taskNameField = new javax.swing.JTextField();
		taskDescriptionLabel = new javax.swing.JLabel();
		taskDescriptionScrollPane = new javax.swing.JScrollPane();
		taskDescriptionArea = new javax.swing.JTextArea();
		mainButtonsPanel = new javax.swing.JPanel();
		closeButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();

		setTitle("Task");
		mainPanel.setLayout(new java.awt.GridBagLayout());

		mainPanel.setBorder(new javax.swing.border.TitledBorder("Task"));
		textPanel.setLayout(new java.awt.GridBagLayout());

		taskNamelabel.setText("Task name:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		textPanel.add(taskNamelabel, gridBagConstraints);

		taskNameField.setColumns(15);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		textPanel.add(taskNameField, gridBagConstraints);

		taskDescriptionLabel.setText("Task description:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		textPanel.add(taskDescriptionLabel, gridBagConstraints);

		taskDescriptionArea.setLineWrap(true);
		taskDescriptionScrollPane.setViewportView(taskDescriptionArea);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.7;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		textPanel.add(taskDescriptionScrollPane, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.4;
		mainPanel.add(textPanel, gridBagConstraints);

		getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

		closeButton.setText("Ok");
		closeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				closeButtonActionPerformed(evt);
			}
		});

		mainButtonsPanel.add(closeButton);

		cancelButton.setText("Cancel");
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});

		mainButtonsPanel.add(cancelButton);

		getContentPane().add(mainButtonsPanel, java.awt.BorderLayout.SOUTH);

		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit()
				.getScreenSize();
		setBounds((screenSize.width - 412) / 2, (screenSize.height - 202) / 2,
				412, 202);
	}// GEN-END:initComponents

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
		this.dispose();
	}// GEN-LAST:event_cancelButtonActionPerformed

	/** Exit the window */
	private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_closeButtonActionPerformed
		String name = taskNameField.getText();
		String description = taskDescriptionArea.getText();
		try {
			if (name != null && !name.equals("") && description != null
					&& !description.equals("")) {
				task.setName(name);
				task.setDescription(description);
				if (!editMode)
					ptPkgReg.addTask(task);
				else
					ptPkgReg.notifyChanges();
				ptPkgReg.storeRegistry();
				this.dispose();
			}
		} catch (jcolibri.cbrcore.exception.InternalException ie) {
			CBRLogger.log("jcolibri.gui.AddTaskFrame",
					"okButtonActionPerformed", ie);
			JOptionPane.showMessageDialog(this, "Error while storing tasks",
					"Error", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_closeButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton cancelButton;

	private javax.swing.JButton closeButton;

	private javax.swing.JPanel mainButtonsPanel;

	private javax.swing.JPanel mainPanel;

	private javax.swing.JTextArea taskDescriptionArea;

	private javax.swing.JLabel taskDescriptionLabel;

	private javax.swing.JScrollPane taskDescriptionScrollPane;

	private javax.swing.JTextField taskNameField;

	private javax.swing.JLabel taskNamelabel;

	private javax.swing.JPanel textPanel;
	// End of variables declaration//GEN-END:variables

}
