package jcolibri.gui;

/**
 * 
 * @author Usuario
 */
public class TextAreaFrame extends javax.swing.JInternalFrame implements
		jcolibri.util.LogListener {
	private static final long serialVersionUID = 1L;

	/** Creates new form TextAreaFrame */
	public TextAreaFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		textAreaScrollPane = new javax.swing.JScrollPane();
		textArea = new javax.swing.JTextArea();
		buttonsPanel = new javax.swing.JPanel();
		Close = new javax.swing.JButton();

		setTitle("Results");
		textAreaScrollPane.setViewportView(textArea);
		textArea.setEditable(false);
		getContentPane().add(textAreaScrollPane, java.awt.BorderLayout.CENTER);

		Close.setText("Close");
		Close.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CloseActionPerformed(evt);
			}
		});

		buttonsPanel.add(Close);

		getContentPane().add(buttonsPanel, java.awt.BorderLayout.SOUTH);

		pack();
	}// GEN-END:initComponents

	private void CloseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CloseActionPerformed
		this.dispose();
	}// GEN-LAST:event_CloseActionPerformed

	public void setText(String text) {
		textArea.setText(text);
	}

	public String getText() {
		return textArea.getText();
	}

	public javax.swing.JTextArea getTextArea() {
		return textArea;
	}

	public void receivedData(String data) {
		textArea.append(data);
		textArea.setCaretPosition(textArea.getText().length());
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton Close;

	private javax.swing.JPanel buttonsPanel;

	private javax.swing.JScrollPane textAreaScrollPane;

	private javax.swing.JTextArea textArea;
	// End of variables declaration//GEN-END:variables

}
