//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2003.09.17 at 10:12:57 CEST 
//

package jcolibri.xml.tasks;

/**
 * Java content class for Tasks element declaration.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this java content object.
 * <p>
 * 
 * <pre>
 *   &lt;element name=&quot;Tasks&quot;&gt;
 *     &lt;complexType&gt;
 *       &lt;complexContent&gt;
 *         &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref=&quot;{}Task&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *           &lt;/sequence&gt;
 *         &lt;/restriction&gt;
 *       &lt;/complexContent&gt;
 *     &lt;/complexType&gt;
 *   &lt;/element&gt;
 * </pre>
 * 
 */
public interface Tasks extends javax.xml.bind.Element,
		jcolibri.xml.tasks.TasksType {

}
