//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.07.27 at 10:46:52 CEST 
//

package jcolibri.xml.methods;

/**
 * Java content class for ContextCondition element declaration.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this java content object.
 * <p>
 * 
 * <pre>
 *   &lt;element name=&quot;ContextCondition&quot; type=&quot;{}ContextConditionType&quot;/&gt;
 * </pre>
 * 
 */
public interface ContextCondition extends javax.xml.bind.Element,
		jcolibri.xml.methods.ContextConditionType {

}
