//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.07.27 at 10:46:52 CEST 
//

package jcolibri.xml.methods;

/**
 * Java content class for annonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this java content object.
 * <p>
 * 
 * <pre>
 *   &lt;complexType&gt;
 *     &lt;complexContent&gt;
 *       &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *         &lt;sequence&gt;
 *           &lt;element name=&quot;Name&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *           &lt;element name=&quot;Description&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *           &lt;element ref=&quot;{}ContextInputPrecondition&quot; minOccurs=&quot;0&quot;/&gt;
 *           &lt;element ref=&quot;{}Type&quot;/&gt;
 *           &lt;element ref=&quot;{}Parameters&quot; minOccurs=&quot;0&quot;/&gt;
 *           &lt;element ref=&quot;{}Competencies&quot;/&gt;
 *           &lt;element ref=&quot;{}SubTasks&quot; minOccurs=&quot;0&quot;/&gt;
 *           &lt;element ref=&quot;{}ContextOutputPostcondition&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/restriction&gt;
 *     &lt;/complexContent&gt;
 *   &lt;/complexType&gt;
 * </pre>
 * 
 */
public interface MethodType {

	java.lang.String getType();

	void setType(java.lang.String value);

	jcolibri.xml.methods.SubTasksType getSubTasks();

	void setSubTasks(jcolibri.xml.methods.SubTasksType value);

	jcolibri.xml.methods.ParametersType getParameters();

	void setParameters(jcolibri.xml.methods.ParametersType value);

	java.lang.String getDescription();

	void setDescription(java.lang.String value);

	jcolibri.xml.methods.ContextInputPreconditionType getContextInputPrecondition();

	void setContextInputPrecondition(
			jcolibri.xml.methods.ContextInputPreconditionType value);

	jcolibri.xml.methods.ContextOutputPostconditionType getContextOutputPostcondition();

	void setContextOutputPostcondition(
			jcolibri.xml.methods.ContextOutputPostconditionType value);

	java.lang.String getName();

	void setName(java.lang.String value);

	jcolibri.xml.methods.CompetenciesType getCompetencies();

	void setCompetencies(jcolibri.xml.methods.CompetenciesType value);

}
