//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.07.27 at 10:46:52 CEST 
//

package jcolibri.xml.methods;

/**
 * Java content class for ParameterType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this java content object.
 * <p>
 * 
 * <pre>
 *   &lt;complexType name=&quot;ParameterType&quot;&gt;
 *     &lt;complexContent&gt;
 *       &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *         &lt;sequence&gt;
 *           &lt;element name=&quot;Name&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *           &lt;element name=&quot;Description&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; minOccurs=&quot;0&quot;/&gt;
 *           &lt;choice&gt;
 *             &lt;element name=&quot;DataType&quot; type=&quot;{}DataTypeType&quot;/&gt;
 *             &lt;element name=&quot;CBRTerm&quot; type=&quot;{}CBRTermType&quot;/&gt;
 *           &lt;/choice&gt;
 *         &lt;/sequence&gt;
 *       &lt;/restriction&gt;
 *     &lt;/complexContent&gt;
 *   &lt;/complexType&gt;
 * </pre>
 * 
 */
public interface ParameterType {

	java.lang.String getDataType();

	void setDataType(java.lang.String value);

	java.lang.String getCBRTerm();

	void setCBRTerm(java.lang.String value);

	java.lang.String getDescription();

	void setDescription(java.lang.String value);

	java.lang.String getName();

	void setName(java.lang.String value);

}
