@echo Note that this application requires Java 1.5+
@echo If you are using the JDBC Connector, you must include the driver as parameter when executing TennisExample.bat
@echo Example:  "c:\jcolibri>TennisExample libs\mysql-connector-java-3.0.11-stable-bin.jar"
@echo ----------------------------
@echo jCOLIBRI Play Tennis example
@echo ----------------------------

cd ..\..\src

@echo Compiling source code generated by jCOLIBRI
javac -classpath ..\libs\;..\bin\ -d ..\bin\ jcolibri\application\PlayTennis\PlayTennis.java


cd ..

@echo Executing CBR Application
set CLASSPATH=libs\jaxb-1.0\jaxb-api.jar;libs\jaxb-1.0\jaxb-ri.jar;libs\jaxb-1.0\jaxb-libs.jar;libs\jaxb-1.0\jaxb-xjc.jar;libs\JRacer2\jracer2.jar;bin\;%1
java -classpath %CLASSPATH% jcolibri.application.PlayTennis.PlayTennis
@pause
cd examples\PlayTennis